version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "docker"
    groups:
      docker-version-dependencies:
        applies-to: version-updates
        patterns:
          - "*"
      docker-security-dependencies:
        applies-to: security-updates
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "github-actions"
    groups:
      actions-version-dependencies:
        applies-to: version-updates
        patterns:
          - "*"
      actions-security-dependencies:
        applies-to: security-updates
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 10
    cooldown:
      default-days: 7
    labels:
      - "dependencies"
      - "npm"
    groups:
      npm-version-dependencies:
        applies-to: version-updates
        patterns:
          - "*"
      npm-security-dependencies:
        applies-to: security-updates
        patterns:
          - "*"

  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 10
    cooldown:
      default-days: 7
    labels:
      - "dependencies"
      - "terraform"
    groups:
      terraform-version-dependencies:
        applies-to: version-updates
        patterns:
          - "*"
      terraform-security-dependencies:
        applies-to: security-updates
        patterns:
          - "*"
