version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "docker"
    groups:
      docker-version-dependencies:
        applies-to: version-updates
        patterns:
          - "*"
      docker-security-dependencies:
        applies-to: security-updates
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "github-actions"
    groups:
      actions-version-dependencies:
        applies-to: version-updates
        patterns:
          - "*"
      actions-security-dependencies:
        applies-to: security-updates
        patterns:
          - "*"
