repos:
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.21.2
    hooks:
      - id: gitleaks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: detect-private-key
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: no-commit-to-branch
  - repo: https://github.com/trufflesecurity/trufflehog
    rev: v3.81.9
    hooks:
      - id: trufflehog
